In [1]:
import numpy as np
import cv2

In [2]:
cap= cv2.VideoCapture(0)

In [3]:
status , pics = cap.read()

In [4]:
status

True

In [5]:
cv2.imshow("my pic", pics)
cv2.waitKey(5000)  #it is in millisecond 5000 millisecond == 5 sec

cv2.destroyAllWindows()

In [6]:
facemodel= cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [7]:
facemodel.detectMultiScale(pics)

array([[409, 178, 168, 168],
       [285, 267, 171, 171]])

In [8]:
len(facemodel.detectMultiScale(pics))

2

In [9]:
status , new = cap.read()

In [10]:
cv2.imshow("my pic", new)
cv2.waitKey(5000)  #it is in millisecond 5000 millisecond == 5 sec

cv2.destroyAllWindows()

In [11]:
 cv2.rectangle(pics,(100,300),(400,500),[0,255,0],2)

array([[[255, 136,  68],
        [255, 138,  73],
        [255, 138,  78],
        ...,
        [255, 204, 138],
        [255, 206, 139],
        [255, 206, 139]],

       [[255, 136,  68],
        [255, 136,  71],
        [255, 136,  75],
        ...,
        [255, 206, 138],
        [255, 208, 141],
        [255, 211, 143]],

       [[255, 139,  72],
        [255, 140,  74],
        [255, 139,  74],
        ...,
        [255, 214, 143],
        [255, 215, 146],
        [255, 217, 148]],

       ...,

       [[255, 159, 129],
        [255, 163, 131],
        [255, 169, 135],
        ...,
        [126,  59,  44],
        [133,  59,  45],
        [138,  64,  50]],

       [[255, 170, 135],
        [255, 172, 136],
        [255, 173, 137],
        ...,
        [128,  60,  46],
        [136,  59,  44],
        [138,  62,  47]],

       [[255, 172, 135],
        [255, 172, 135],
        [255, 175, 137],
        ...,
        [127,  57,  43],
        [138,  59,  44],
        [139,  61,  45]]

In [12]:
#face ke around hi krna he to coordinate chiye honge face ke jo ki haarcascade dega hmee
x1=190
y1=174
x2=190+179
y2=174+179
cv2.rectangle(pics,(x1,y1),(x2,y2),[0,255,0],2)

array([[[255, 136,  68],
        [255, 138,  73],
        [255, 138,  78],
        ...,
        [255, 204, 138],
        [255, 206, 139],
        [255, 206, 139]],

       [[255, 136,  68],
        [255, 136,  71],
        [255, 136,  75],
        ...,
        [255, 206, 138],
        [255, 208, 141],
        [255, 211, 143]],

       [[255, 139,  72],
        [255, 140,  74],
        [255, 139,  74],
        ...,
        [255, 214, 143],
        [255, 215, 146],
        [255, 217, 148]],

       ...,

       [[255, 159, 129],
        [255, 163, 131],
        [255, 169, 135],
        ...,
        [126,  59,  44],
        [133,  59,  45],
        [138,  64,  50]],

       [[255, 170, 135],
        [255, 172, 136],
        [255, 173, 137],
        ...,
        [128,  60,  46],
        [136,  59,  44],
        [138,  62,  47]],

       [[255, 172, 135],
        [255, 172, 135],
        [255, 175, 137],
        ...,
        [127,  57,  43],
        [138,  59,  44],
        [139,  61,  45]]

In [13]:
cv2.imshow("my pic", pics)
cv2.waitKey(5000)  #it is in millisecond 5000 millisecond == 5 sec

cv2.destroyAllWindows()

In [14]:
myfacecoord= facemodel.detectMultiScale(pics)
x1= myfacecoord[0][0]
y1= myfacecoord[0][1]
x2= myfacecoord[0][0] + myfacecoord[0][2]
y2= myfacecoord[0][0] + myfacecoord[0][3]
cv2.rectangle(pics,(x1,y1),(x2,y2),[0,255,0],2)

array([[[255, 136,  68],
        [255, 138,  73],
        [255, 138,  78],
        ...,
        [255, 204, 138],
        [255, 206, 139],
        [255, 206, 139]],

       [[255, 136,  68],
        [255, 136,  71],
        [255, 136,  75],
        ...,
        [255, 206, 138],
        [255, 208, 141],
        [255, 211, 143]],

       [[255, 139,  72],
        [255, 140,  74],
        [255, 139,  74],
        ...,
        [255, 214, 143],
        [255, 215, 146],
        [255, 217, 148]],

       ...,

       [[255, 159, 129],
        [255, 163, 131],
        [255, 169, 135],
        ...,
        [126,  59,  44],
        [133,  59,  45],
        [138,  64,  50]],

       [[255, 170, 135],
        [255, 172, 136],
        [255, 173, 137],
        ...,
        [128,  60,  46],
        [136,  59,  44],
        [138,  62,  47]],

       [[255, 172, 135],
        [255, 172, 135],
        [255, 175, 137],
        ...,
        [127,  57,  43],
        [138,  59,  44],
        [139,  61,  45]]

In [ ]:
while True:
    status , pics = cap.read()
    myfacecoord= facemodel.detectMultiScale(pics)
    if len(myfacecoord)==1:
        x1= myfacecoord[0][0]
        y1= myfacecoord[0][1]
        x2= myfacecoord[0][0] + myfacecoord[0][2]
        y2= myfacecoord[0][0] + myfacecoord[0][3]
        cv2.rectangle(pics,(x1,y1),(x2,y2),[0,255,0],2)

    cv2.imshow("my pic", pics)
    if cv2.waitKey() ==13:  #it is in millisecond 5000 millisecond == 5 sec
        break

cv2.destroyAllWindows()