In [7]:
import cv2

In [23]:
cap= cv2.VideoCapture(0)
#we can connect hrogh mobile cam by pasting mobile url

In [24]:
status , photo = cap.read()

In [10]:
status

True

In [5]:
#live streeaming:

while True:
    status, pic = cap.read()
    cv2.imshow("my pic", pic)
    if cv2.waitKey(1) ==13:
        break

cv2.destroyAllWindows()

In [8]:
photo.ndim

3

In [24]:
import numpy as np

In [21]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [25]:
aa = np.array([[1,2,3,4],
              [3,4,5,6],
              [4,6,7,8]])

In [27]:
aa.shape

(3, 4)

In [31]:
aa[: ,1:3]
#imahe ka color bhi aise hi change krene kisi bhi image me uske numpy array se ched chaad krke

array([[2, 3],
       [4, 5],
       [6, 7]])

In [32]:
photo

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [149, 141, 142],
        [153, 143, 144],
        [155, 146, 147]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [141, 136, 136],
        [147, 140, 141],
        [151, 144, 144]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [138, 137, 137],
        [141, 138, 138],
        [146, 144, 144]],

       ...,

       [[236, 214, 197],
        [233, 213, 197],
        [229, 210, 194],
        ...,
        [ 87,  50,  56],
        [ 85,  47,  55],
        [ 90,  51,  60]],

       [[233, 204, 188],
        [230, 204, 189],
        [220, 196, 181],
        ...,
        [ 88,  51,  55],
        [ 86,  49,  54],
        [ 92,  54,  60]],

       [[229, 196, 181],
        [228, 199, 184],
        [225, 199, 185],
        ...,
        [ 86,  49,  52],
        [ 88,  51,  55],
        [ 92,  55,  58]]

In [33]:
photo[10,30] #apnne tenth row aur 30th column ka pixel box utha liya jisme apnne uske rgb show krvaaye he

array([250, 231, 248], dtype=uint8)

In [25]:
cv2.imshow("my pic", photo)
cv2.waitKey(5000)  
cv2.destroyAllWindows()

In [12]:
photo[:,:,1:3] =0  #BGR me blue blue rhne diya bki ki aisi ki taisi krid

In [17]:
photo[:,:,0]+50

array([[ 21,  19,  20, ..., 226, 230, 232],
       [ 17,  15,  20, ..., 224, 230, 231],
       [ 11,  17,  22, ..., 223, 227, 227],
       ...,
       [172, 178, 180, ...,  49,  49,  49],
       [172, 177, 178, ...,  49,  49,  49],
       [172, 177, 174, ...,  49,  49,  49]], dtype=uint8)

In [19]:
photo

array([[[227, 202, 211],
        [225, 206, 211],
        [226, 212, 213],
        ...,
        [176, 171, 176],
        [180, 169, 176],
        [182, 171, 179]],

       [[223, 198, 207],
        [221, 201, 207],
        [226, 210, 212],
        ...,
        [174, 170, 175],
        [180, 171, 179],
        [181, 172, 180]],

       [[217, 192, 201],
        [223, 201, 207],
        [228, 209, 212],
        ...,
        [173, 171, 177],
        [177, 173, 180],
        [177, 173, 180]],

       ...,

       [[122, 102,  70],
        [128, 106,  73],
        [130, 106,  71],
        ...,
        [255, 240, 216],
        [255, 241, 214],
        [255, 242, 215]],

       [[122, 101,  75],
        [127, 106,  78],
        [128, 106,  76],
        ...,
        [255, 244, 219],
        [255, 246, 219],
        [255, 242, 215]],

       [[122, 100,  77],
        [127, 105,  80],
        [124, 103,  76],
        ...,
        [255, 245, 221],
        [255, 246, 219],
        [255, 242, 215]]

In [20]:
#agr me hr pixel ke rgb ko avg krke single valur bnaadu to me 3d ko 2d me convert kr skta hu 
#grayscale bn jaayega maybe:
graypho=cv2.cvtColor(photo , cv2.COLOR_BGR2GRAY)
#rgb image hmeha 2d image hi rhegi

In [22]:
cv2.imshow("my pic", graypho)
cv2.waitKey(5000)  
cv2.destroyAllWindows()

# Object Detection 

In [26]:
#object detection: for human it is very easy but for computers it is very difficult because images are munpy array for mach.
#most widely used usecase maybe known as self learning cars it uses object detection to take decisions
#human attribute detection can be fetched from Haarcascade
#like eye ko detect krke uspe overlay lgaa denge to filter lgg jaayega.