# Project Brief:

In [ ]:
#in real world we mostly use multi variable linear regression.
#by single variable we cannot make accurate model in real life.
#there are several variables which can imhpact the target value of model , this is known as multivariate linear regression.
#y = actual answer..
#y' = predicted answer
#our target is to find y.
#here in this example or database we can generate function like : y= c1*x1 + c2*x2 +bias
#pathfinder bnna skte he isme apn log...
#like What you want to be
#suicide management 


In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [42]:
ds=pd.read_excel("PCENEW.xlsx")
ds

name  cafe  hrs  marks
0      harry     0    2     20
1      ayush     0    4     40
2      rahul    10    4     30
3       ajay    20    4     20
4  divyanshu    10    5     40
5     ishant    15    5     35

In [43]:
ds.shape

(6, 4)

In [44]:
X = ds[["cafe","hrs"]]
X

cafe  hrs
0     0    2
1     0    4
2    10    4
3    20    4
4    10    5
5    15    5

In [45]:
y = ds["marks"]
y

0    20
1    40
2    30
3    20
4    40
5    35
Name: marks, dtype: int64

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
model = LinearRegression()

In [48]:
model.fit(X,y)

LinearRegression()

In [49]:
model.predict([[20,5]])

C:\Users\91800\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([30.])

In [50]:
model.coef_

array([-1., 10.])

In [51]:
model.intercept_

-1.0658141036401503e-14

In [53]:
model.predict([[0,2]])

C:\Users\91800\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([20.])